export type FileFormat = 'PDF' | 'DOCX' | 'XLSX' | 'PPTX'

// Short content snippets used for search result previews
export const DOCUMENT_SNIPPETS: Record<string, string> = {
  '1':  'Diese Richtlinie regelt alle Aspekte internationaler Mitarbeiterversetzungen bei Siemens AG, inklusive steuerlicher Behandlung, Sozialversicherungspflichten und Umzugskostenvergütung gemäß BGB § 611a.',
  '2':  'Veraltete Fassung der Versetzungsrichtlinie für internationale Einsätze. Enthält Regelungen zu Relocation-Zuschüssen und steuerlicher Optimierung bei Auslandsentsendungen der Siemens AG.',
  '3':  'Allianz SE definiert Bedingungen für Mitarbeiterumzüge ins Ausland gemäß EU-Entsenderichtlinie. Moving Allowances, Sozialversicherung und steuerliche Behandlung im europäischen Wirtschaftsraum.',
  '4':  'Regelungen zur mobilen Arbeit und Homeoffice bei grenzüberschreitenden Tätigkeiten für Deutsche Telekom AG-Mitarbeiter gemäß Arbeitszeitgesetz § 2 ArbZG und steuerlichen Implikationen.',
  '5':  'KPMG-Leitfaden zur steuerlichen Behandlung internationaler Mitarbeitereinsätze nach Einkommensteuergesetz § 1 EStG. Steuerpflicht, Freistellungsregelungen und Doppelbesteuerung bei Auslandseinsätzen.',
  '6':  'Veraltete KPMG-Expertise zur Besteuerung von Auslandseinsätzen gemäß § 1 EStG. Frühere Einkommensteuerschwellen und steuerliche Pflichten für international tätige Mitarbeiter.',
  '7':  'Bundesministerium der Finanzen: Leitfaden zum Doppelbesteuerungsabkommen zwischen Deutschland und Großbritannien. Einkommensaufteilung nach Art. 4 DBA UK-DE und steuerliche Ansässigkeitsregeln.',
  '8':  'PwC Germany analysiert lohnsteuerliche Anforderungen bei kurzfristigen internationalen Entsendungen. Quellensteuerabzug nach § 38 EStG, Arbeitgeberpflichten und Withholding-Tax-Verfahren.',
  '9':  'OECD Model Tax Convention Artikel 15 erklärt die 183-Tage-Regelung für international mobile Mitarbeiter. Anwendungsbeispiele zur Bestimmung der steuerlichen Arbeitgebereigenschaft und Quellenstaatbesteuerung.',
  '10': 'AOK Germany erläutert sozialversicherungsrechtliche Pflichten bei EU-weiten Tätigkeiten gemäß Regulation 883/2004. A1-Bescheinigungen, Beitragspflichten und Krankenversicherungsschutz im Ausland.',
  '11': 'Bosch GmbH kombiniert HR-Management und steuerliche Aspekte kurzfristiger Auslandsentsendungen. Per-Diem-Regelungen, § 50d EStG-Anforderungen und internationale Compliance für Kurzzeitentsendungen.',
  '12': 'EY Germany analysiert Compliance-Risiken bei grenzüberschreitenden Beschäftigungsverhältnissen. EU-Entsenderichtlinie 96/71/EC, Risikoexposition bis 90.000 EUR und regulatorische Anforderungen.',
  '13': 'SAP SE-Richtlinie zur internationalen Gehaltsstruktur bei Auslandseinsätzen. Vergütungsbestandteile, Gehaltsanpassungen, Bonusregelungen und Mitbestimmungsrechte gemäß § 87 BetrVG.',
  '14': 'Lufthansa Group Spesenregelung für Geschäftsreisen und internationale Einsätze. Tagegeldregelungen, Fahrtkosten, Hotelkosten und steuerliche Absetzbarkeit gemäß Einkommensteuergesetz § 9.',
  '15': 'Bundeszentralamt für Steuern definiert Meldepflichten für international tätige Steuerpflichtige. Abgabenordnung § 138 AO, Wegzugsmeldung, Steuernummernregistrierung und Auskunftspflichten.',
  '16': 'Bundesfinanzhof-Leitfaden zur steuerlichen Ansässigkeit nach Abgabenordnung § 8 und § 9 AO. Wohnsitz- und Aufenthaltskonzepte zur Bestimmung unbeschränkter Steuerpflicht in Deutschland.',
  '17': 'Deloitte Germany erläutert Quellensteuerregelungen für nicht ansässige Mitarbeiter nach § 49 EStG. Withholding-Tax-Pflichten, Freistellungsanträge und Doppelbesteuerungsabkommen für internationale Fachkräfte.',
  '18': 'Europäische Kommission: Leitfaden zur EU-Arbeitnehmerentsendung gemäß Richtlinie 2018/957. Mindestlohnregelungen, maximale Entsendedauer und Sozialschutz für entsandte Arbeitnehmer innerhalb der EU.',
  '19': 'Accenture GmbH: Veralteter Compliance-Leitfaden für internationale Mitarbeitermobilität gemäß EU-Entsenderichtlinie 96/71/EC. Risikoexposition, Behördenpflichten und regulatorische Anforderungen für global mobile Mitarbeiter.',
  '20': 'McKinsey & Company analysiert steuerliche und HR-Auswirkungen kurzfristiger Mitarbeiterversetzungen. Gesamtkostenimpact, § 42d EStG-Haftungsrisiken und strategische Empfehlungen für globale Mobilitätsprogramme.',
}
export type DocumentStatus = 'Approved' | 'Draft' | 'Superseded'

export interface MetadataDocument {
  _id: string
  name: string
  domain: string
  documentType: string
  status: DocumentStatus
  namedEntity: string
  namedEntityId: string
  year: number
  monetaryAmounts: number
  currency: string
  monetaryTypes: string
  lawType: string
  citations: string
  jurisdiction: string
  uploadedDate: string
  fileSize: string
  fileFormat: FileFormat
  label?: string
  tagList?: { text: string; style: string; variant?: string }[] | null
}

export const documents: MetadataDocument[] = [
  {
    _id: '1',
    name: 'Richtlinie zur internationalen Mitarbeiterversetzung (2025)',
    domain: 'HR',
    documentType: 'HR Policy',
    status: 'Approved',
    namedEntity: 'Siemens AG',
    namedEntityId: 'DE-CORP-001',
    year: 2025,
    monetaryAmounts: 5000,
    currency: 'EUR',
    monetaryTypes: 'Relocation allowance',
    lawType: 'Regulation',
    citations: 'BGB § 611a',
    jurisdiction: 'Germany',
    uploadedDate: '2025-03-12',
    fileSize: '2.4 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '2',
    name: 'Richtlinie zur internationalen Mitarbeiterversetzung (2022)',
    domain: 'HR',
    documentType: 'HR Policy',
    status: 'Superseded',
    namedEntity: 'Siemens AG',
    namedEntityId: 'DE-CORP-001',
    year: 2022,
    monetaryAmounts: 4000,
    currency: 'EUR',
    monetaryTypes: 'Relocation allowance',
    lawType: 'Regulation',
    citations: 'BGB § 611a',
    jurisdiction: 'Germany',
    uploadedDate: '2022-01-18',
    fileSize: '2.1 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '3',
    name: 'Mitarbeiter-Umzugsrichtlinie für Auslandsentsendungen',
    domain: 'HR',
    documentType: 'HR Policy',
    status: 'Approved',
    namedEntity: 'Allianz SE',
    namedEntityId: 'DE-CORP-002',
    year: 2024,
    monetaryAmounts: 3000,
    currency: 'EUR',
    monetaryTypes: 'Moving allowance',
    lawType: 'Directive',
    citations: 'EU Posting of Workers Directive',
    jurisdiction: 'EU',
    uploadedDate: '2024-06-10',
    fileSize: '3.0 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '4',
    name: 'Homeoffice-Regelung für grenzüberschreitende Tätigkeiten',
    domain: 'HR',
    documentType: 'HR Policy',
    status: 'Draft',
    namedEntity: 'Deutsche Telekom AG',
    namedEntityId: 'DE-CORP-003',
    year: 2025,
    monetaryAmounts: 0,
    currency: 'EUR',
    monetaryTypes: 'None',
    lawType: 'Regulation',
    citations: '§ 2 ArbZG',
    jurisdiction: 'Germany',
    uploadedDate: '2025-09-01',
    fileSize: '1.8 MB',
    fileFormat: 'DOCX',
    label: 'Signature Required',
  },
  {
    _id: '5',
    name: 'Steuerliche Behandlung von Auslandseinsätzen',
    domain: 'Tax',
    documentType: 'Tax Guidance',
    status: 'Approved',
    namedEntity: 'KPMG GmbH',
    namedEntityId: 'DE-CONS-010',
    year: 2024,
    monetaryAmounts: 75000,
    currency: 'EUR',
    monetaryTypes: 'Taxable income threshold',
    lawType: 'Law',
    citations: '§ 1 EStG',
    jurisdiction: 'Germany',
    uploadedDate: '2024-04-20',
    fileSize: '4.2 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '6',
    name: 'Steuerliche Behandlung von Auslandseinsätzen',
    domain: 'Tax',
    documentType: 'Tax Guidance',
    status: 'Superseded',
    namedEntity: 'KPMG GmbH',
    namedEntityId: 'DE-CONS-010',
    year: 2019,
    monetaryAmounts: 60000,
    currency: 'EUR',
    monetaryTypes: 'Taxable income threshold',
    lawType: 'Law',
    citations: '§ 1 EStG',
    jurisdiction: 'Germany',
    uploadedDate: '2019-07-15',
    fileSize: '3.9 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '7',
    name: 'Doppelbesteuerungsabkommen Deutschland–UK Leitfaden',
    domain: 'Tax',
    documentType: 'Tax Treaty Guide',
    status: 'Approved',
    namedEntity: 'Federal Ministry of Finance Germany',
    namedEntityId: 'DE-GOV-001',
    year: 2023,
    monetaryAmounts: 120000,
    currency: 'EUR',
    monetaryTypes: 'Income allocation',
    lawType: 'Treaty',
    citations: 'Art. 4 DBA UK–DE',
    jurisdiction: 'Germany / UK',
    uploadedDate: '2023-05-11',
    fileSize: '5.1 MB',
    fileFormat: 'PDF',
    label: 'Regulation Change',
  },
  {
    _id: '8',
    name: 'Lohnsteuerliche Pflichten bei kurzfristiger Entsendung',
    domain: 'Tax',
    documentType: 'Payroll Tax Guidance',
    status: 'Approved',
    namedEntity: 'PwC Germany',
    namedEntityId: 'DE-CONS-011',
    year: 2024,
    monetaryAmounts: 45000,
    currency: 'EUR',
    monetaryTypes: 'Withholding tax base',
    lawType: 'Law',
    citations: '§ 38 EStG',
    jurisdiction: 'Germany',
    uploadedDate: '2024-02-02',
    fileSize: '3.3 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '9',
    name: '183-Tage-Regelung Anwendung und Beispiele',
    domain: 'Tax',
    documentType: 'Tax Rule Explanation',
    status: 'Approved',
    namedEntity: 'OECD',
    namedEntityId: 'INT-ORG-001',
    year: 2023,
    monetaryAmounts: 0,
    currency: 'EUR',
    monetaryTypes: 'None',
    lawType: 'Regulation',
    citations: 'OECD Model Tax Convention Art. 15',
    jurisdiction: 'International',
    uploadedDate: '2023-09-18',
    fileSize: '2.7 MB',
    fileFormat: 'PDF',
    label: 'Appeal Possible',
  },
  {
    _id: '10',
    name: 'Sozialversicherungsrecht bei grenzüberschreitender Tätigkeit',
    domain: 'HR',
    documentType: 'Compliance Guide',
    status: 'Approved',
    namedEntity: 'AOK Germany',
    namedEntityId: 'DE-ORG-020',
    year: 2024,
    monetaryAmounts: 0,
    currency: 'EUR',
    monetaryTypes: 'Contributions',
    lawType: 'Regulation',
    citations: 'EU Regulation 883/2004',
    jurisdiction: 'EU',
    uploadedDate: '2024-08-30',
    fileSize: '3.6 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '11',
    name: 'Kurzfristige Auslandsentsendung: HR- und Steuerliche Übersicht',
    domain: 'HR/Tax',
    documentType: 'Combined Policy',
    status: 'Approved',
    namedEntity: 'Bosch GmbH',
    namedEntityId: 'DE-CORP-004',
    year: 2025,
    monetaryAmounts: 2000,
    currency: 'EUR',
    monetaryTypes: 'Per diem allowance',
    lawType: 'Directive',
    citations: '§ 50d EStG',
    jurisdiction: 'Germany',
    uploadedDate: '2025-01-10',
    fileSize: '4.0 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '12',
    name: 'Grenzüberschreitende Beschäftigung: Risiken und Richtlinien',
    domain: 'HR/Tax',
    documentType: 'Compliance Guide',
    status: 'Draft',
    namedEntity: 'EY Germany',
    namedEntityId: 'DE-CONS-012',
    year: 2025,
    monetaryAmounts: 90000,
    currency: 'EUR',
    monetaryTypes: 'Risk exposure',
    lawType: 'Regulation',
    citations: 'EU Posting Directive 96/71/EC',
    jurisdiction: 'EU',
    uploadedDate: '2025-07-14',
    fileSize: '4.5 MB',
    fileFormat: 'PDF',
    label: 'Deadline Due',
  },
  {
    _id: '13',
    name: 'Vergütungsstruktur bei internationalem Einsatz',
    domain: 'HR',
    documentType: 'Salary Policy',
    status: 'Approved',
    namedEntity: 'SAP SE',
    namedEntityId: 'DE-CORP-005',
    year: 2024,
    monetaryAmounts: 85000,
    currency: 'EUR',
    monetaryTypes: 'Salary',
    lawType: 'Regulation',
    citations: '§ 87 BetrVG',
    jurisdiction: 'Germany',
    uploadedDate: '2024-03-22',
    fileSize: '2.9 MB',
    fileFormat: 'XLSX',
  },
  {
    _id: '14',
    name: 'Reisekosten- und Spesenrichtlinie',
    domain: 'HR',
    documentType: 'Expense Policy',
    status: 'Approved',
    namedEntity: 'Lufthansa Group',
    namedEntityId: 'DE-CORP-006',
    year: 2023,
    monetaryAmounts: 150,
    currency: 'EUR',
    monetaryTypes: 'Travel allowance',
    lawType: 'Regulation',
    citations: 'EStG § 9',
    jurisdiction: 'Germany',
    uploadedDate: '2023-02-11',
    fileSize: '2.2 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '15',
    name: 'Steuerliche Meldepflichten bei Auslandseinsätzen',
    domain: 'Tax',
    documentType: 'Tax Compliance Guide',
    status: 'Approved',
    namedEntity: 'Bundeszentralamt für Steuern',
    namedEntityId: 'DE-GOV-002',
    year: 2024,
    monetaryAmounts: 0,
    currency: 'EUR',
    monetaryTypes: 'None',
    lawType: 'Law',
    citations: '§ 138 AO',
    jurisdiction: 'Germany',
    uploadedDate: '2024-11-05',
    fileSize: '3.1 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '16',
    name: 'Definition der steuerlichen Ansässigkeit in Deutschland',
    domain: 'Tax',
    documentType: 'Legal Definition Guide',
    status: 'Approved',
    namedEntity: 'Bundesfinanzhof',
    namedEntityId: 'DE-COURT-001',
    year: 2023,
    monetaryAmounts: 0,
    currency: 'EUR',
    monetaryTypes: 'None',
    lawType: 'Court ruling',
    citations: 'AO § 8, § 9',
    jurisdiction: 'Germany',
    uploadedDate: '2023-06-19',
    fileSize: '2.5 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '17',
    name: 'Quellensteuerregelungen für internationale Mitarbeiter',
    domain: 'Tax',
    documentType: 'Tax Regulation Guide',
    status: 'Approved',
    namedEntity: 'Deloitte Germany',
    namedEntityId: 'DE-CONS-013',
    year: 2024,
    monetaryAmounts: 60000,
    currency: 'EUR',
    monetaryTypes: 'Withholding tax',
    lawType: 'Law',
    citations: '§ 49 EStG',
    jurisdiction: 'Germany',
    uploadedDate: '2024-07-21',
    fileSize: '3.8 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '18',
    name: 'Leitfaden zur Mitarbeiterentsendung innerhalb der EU',
    domain: 'HR',
    documentType: 'HR Guide',
    status: 'Approved',
    namedEntity: 'European Commission',
    namedEntityId: 'EU-ORG-001',
    year: 2023,
    monetaryAmounts: 0,
    currency: 'EUR',
    monetaryTypes: 'None',
    lawType: 'Directive',
    citations: 'EU Directive 2018/957',
    jurisdiction: 'EU',
    uploadedDate: '2023-10-10',
    fileSize: '4.4 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '19',
    name: 'Compliance-Leitfaden für internationale Mitarbeitermobilität',
    domain: 'HR/Tax',
    documentType: 'Compliance Guide',
    status: 'Superseded',
    namedEntity: 'Accenture GmbH',
    namedEntityId: 'DE-CORP-007',
    year: 2021,
    monetaryAmounts: 70000,
    currency: 'EUR',
    monetaryTypes: 'Compliance risk exposure',
    lawType: 'Regulation',
    citations: 'EU Posting Directive 96/71/EC',
    jurisdiction: 'EU',
    uploadedDate: '2021-04-08',
    fileSize: '3.7 MB',
    fileFormat: 'PDF',
  },
  {
    _id: '20',
    name: 'Steuer- und HR-Auswirkungen temporärer Versetzungen',
    domain: 'HR/Tax',
    documentType: 'Analytical Report',
    status: 'Draft',
    namedEntity: 'McKinsey & Company',
    namedEntityId: 'DE-CONS-014',
    year: 2025,
    monetaryAmounts: 110000,
    currency: 'EUR',
    monetaryTypes: 'Total cost impact',
    lawType: 'Directive',
    citations: '§ 42d EStG',
    jurisdiction: 'Germany / EU',
    uploadedDate: '2025-08-19',
    fileSize: '5.0 MB',
    fileFormat: 'PPTX',
  },
]
